server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  #config: classpath:logback-spring.xml
  config: /seata-server/resources/seata.logback.xml
  file:
    path: ${user.home}/logs/seata

console:
  user:
    username: seata
    password: seata

seata:
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: file
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: nacos
    nacos:
      server-addr: 192.168.31.146:8848
      namespace:
      group: SEATA_GROUP
      username: nacos
      password: nacos

  store:
    # support: file 、 db 、 redis
    mode: redis
    redis:
      mode: single
      type: lua
      database: 1
      min-conn: 10
      max-conn: 100
      password:
      max-total: 100
      query-limit: 2000
      single:
        host: 192.168.31.146
        port: 6379
  #  server:
  #    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login,/metadata/v1/**