spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 127.0.0.1
      jedis:
        pool:
          enabled: true


