name: backend server build
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "docker version to release"
    
env:
  REGISTRY: ghcr.io
jobs:
  backend-build:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        settings:
            - service: order
            - service: product
            - service: others
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: 17
            cache: 'maven'
            cache-dependency-path: 'cloud/pom.xml'       

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GithubPackages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: make release-backend
      -
        name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: backend/docker
          push: true        
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.REGISTRY }}/timzaak/hp-cloud-${{matrix.settings.service}}:${{github.event.inputs.version}}, ${{ env.REGISTRY }}/timzaak/hp-cloud-${{matrix.settings.service}}:latest